class Selectors:
    username_textfield = "//input[@id='user-name']"
    username_passwordfield = "//input[@id='password']"
    login_button = "//input[@id='login-button']"
    sort_active_option = "//select[@class='product_sort_container']/option[text()='Price (high to low)']"
    add_to_cart_item_1 = "//button[@id='add-to-cart-sauce-labs-bolt-t-shirt']"
    add_to_cart_item_2 = "// button[@id='add-to-cart-sauce-labs-onesie']"
    add_to_cart_item_3 = "//button[@id='add-to-cart-sauce-labs-bike-light']"
    shopping_cart = "//a[@class='shopping_cart_link']"
    checkout_order_button = "//button[@id='checkout']"
    first_name = "//input[@id='first-name']"
    last_name = "//input[@id='last-name']"
    postal_code = "//input[@id='postal-code']"
    continue_button = "//input[@id='continue']"
    summary_total = "//div[@class='summary_total_label'][normalize-space()='Total: $36.69']"
    summary_subtotal = "//div[@class='summary_subtotal_label'][normalize-space()='Item total: $33.97']"
    summary_tax = " //div[@class='summary_tax_label'][normalize-space()='Tax: $2.72']"
